apiVersion: v1
kind: Pod
metadata:
  name: pod-with-quota
spec:
  containers:
  - name: test-box
    image: busybox
    command: ["/bin/sleep", "999999"]
    resources:
      limits:
        memory: "800Mi"
        cpu: "800m"
      requests:
        memory: "600Mi"
        cpu: "400m"
