kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: ns-admin
  namespace: namespace_name
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["*"]
