kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: ceph-csi
  name: rbd-external-provisioner-cfg
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "create", "delete"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "watch", "list", "delete", "update", "create"]
