apiVersion: v1
kind: Service
metadata:
  name: csi-metrics-rbdplugin
  labels:
    app: csi-metrics
  namespace: ceph-csi
spec:
  ports:
  - name: http-metrics
    port: 8080
    protocol: TCP
    targetPort: 8680
  selector:
    app: csi-rbdplugin
