apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: rbd
provisioner: rbd.csi.ceph.com
parameters:
  clusterID: a3f09810-e2b2-11ea-b7d2-080027589fef
  pool: cka
  imageFeatures: "layering"
  csi.storage.k8s.io/provisioner-secret-name: csi-rbd-secret
  csi.storage.k8s.io/provisioner-secret-namespace: default
  csi.storage.k8s.io/node-stage-secret-name: csi-rbd-secret
  csi.storage.k8s.io/node-stage-secret-namespace: default
  csi.storage.k8s.io/controller-expand-secret-name: csi-rbd-secret
  csi.storage.k8s.io/controller-expand-secret-namespace: default
reclaimPolicy: Delete
allowVolumeExpansion: true
mountOptions:
- discard

