kind: PersistentVolume
apiVersion: v1
metadata:
  name: wordpress
  labels:
    type: web
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/wordpress"
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress
  labels:
    app: wordpress
    component: wordpress
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      type: web

---
apiVersion: v1
kind: Secret
metadata:
  name: mysql
  labels:
    app: wordpress
    component: mysql
type: Opaque
stringData:
  password: "123"

---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
    component: wordpress
spec:
  ports:
    - port: 80
  selector:
    app: wordpress
    component: wordpress

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
    component: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
      component: wordpress
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        component: wordpress
    spec:
      containers:
      - image: wordpress:5.5-apache
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: mysql-0.mysql
        - name: WORDPRESS_DB_USER
          value: wordpress
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql
              key: password
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wordpress
          mountPath: /var/www/html
      volumes:
      - name: wordpress
        persistentVolumeClaim:
          claimName: wordpress
