apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    component: wordpress
spec:
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
    name: wordpress
  selector:
    component: wordpress
  type: NodePort
