apiVersion: v1
kind: Service
metadata:
  name: web-server-green
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/role: green
  ports:
    - port: 80
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server-1.19
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/version: 1.19.6
    app.kubernetes.io/role: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx
      app.kubernetes.io/version: 1.19.6
      app.kubernetes.io/role: green
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx
        app.kubernetes.io/version: 1.19.6
        app.kubernetes.io/role: green
      name: test-nginx
      namespace: default
    spec:
      containers:
      - image: nginx:1.19.6-alpine
        name: test-nginx
        volumeMounts:
        - mountPath: /usr/share/nginx/html/test
          name: test-volume
        ports:
        - containerPort: 80
        imagePullPolicy: IfNotPresent
      initContainers:
      - image: alpine
        name: initcontainer
        command: ["/bin/sh", "-c", "--"]
        args: ["echo This is test page for nginx v1.19.6! > /usr/share/nginx/html/test/index.html"]
        volumeMounts:
        - mountPath: /usr/share/nginx/html/test
          name: test-volume
        imagePullPolicy: IfNotPresent
      volumes:
      - name: test-volume
        emptyDir: {}

