apiVersion: v1
kind: Pod
metadata:
  name: pod-with-hostport
spec:
  containers:
  - image: nginx:stable-alpine
    name: nginx
    ports:
    - containerPort: 80
      hostPort: 80
      protocol: TCP
